/**
 * Jupyter Labs — centralized content & curated editorial imagery.
 * Images are high-end Unsplash editorial photographs (wellness, botanical,
 * skincare, lab). Every <Img> degrades to an on-brand gradient if a source
 * is ever unavailable, so the experience never shows a broken asset.
 */

const U = (id: string, w = 1400, q = 80) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=${q}`

export const IMG = {
  heroProduct: U('1620916566398-39f1143ab7be', 1100),
  heroAtmosphere: U('1556228720-195a672e8a03', 1600),
  difference: U('1556228578-8c89e6adf883', 1200),
  lifestyle1: U('1540555700478-4be289fbecef', 1400),
  lifestyle2: U('1591343395082-e120087004b4', 1200),
  lifestyle3: U('1545205597-3d9d02c29597', 1000),
  science: U('1532187863486-abf9dbad1b69', 1400),
  scienceLab: U('1581093588401-fbb62a02f120', 1200),
  about: U('1517960413843-0aee8e2b3285', 1400),
  sustainability: U('1542601906990-b4d3fb778b09', 1400),
  ingredientAdaptogen: U('1515823064-d6e0c04616a7', 900),
  ingredientCollagen: U('1559827260-dc66d52bef19', 900),
  ingredientOmega: U('1559181567-c3190ca9959b', 900),
  ingredientGreens: U('1416879595882-3373a0480b5b', 900),
} as const

export const PRODUCTS = [
  {
    id: 'bpc-157',
    slug: 'bpc-157-tb-500',
    name: 'BPC-157 & TB-500',
    tagline: 'Recovery · Joint · Tissue',
    category: 'Tissue Repair',
    desc: 'A research-grade peptide studied for tissue repair, joint recovery and connective-tissue support in pre-clinical models.',
    longDesc:
      'A synergistic research blend of BPC-157 (Body Protection Compound 157) — a synthetic pentadecapeptide derived from a protective sequence found in human gastric juice — and TB-500 (Thymosin Beta-4), a naturally-occurring peptide studied for actin-binding and cellular migration. Delivered pre-filled into an Alluvi research pen (4 × 10mg doses) for laboratory study of soft-tissue and joint-recovery pathways.',
    price: 130,
    currency: 'USD',
    accent: '#0f766e',
    tint: '#E6F1EF',
    image: '/images/products/bpc-front.webp',
    gallery: [
      '/images/products/bpc-front.webp',
      '/images/products/bpc-open.webp',
      '/images/products/bpc-pen.webp',
      '/images/products/bpc-uv.webp',
    ],
    stat: '99.2% HPLC purity',
    specs: [
      { k: 'Purity', v: '99.21%+ HPLC verified' },
      { k: 'Testing', v: 'Janoshik independent COA' },
      { k: 'Format', v: 'Pre-filled research pen · 4 × 10mg' },
      { k: 'Storage', v: '2–8°C · Do not freeze' },
      { k: 'Shelf life', v: '24–36 months sealed' },
    ],
    mechanism:
      'BPC-157 is studied for its interaction with angiogenic pathways (VEGF, growth-factor upregulation) and nitric oxide signalling, while TB-500 is investigated for actin sequestration and endothelial cell migration. In tandem, researchers model potential synergistic effects on granulation, revascularisation and connective-tissue remodelling.',
    benefits: [
      'Tissue-repair pathway research',
      'Blood-vessel growth modelling',
      'Inflammatory-response modulation',
      'Muscle, tendon and ligament recovery studies',
      'Gut-barrier integrity investigations',
      'Post-injury remodelling protocols',
    ],
    applications: [
      'Pre-clinical soft-tissue recovery studies',
      'In-vitro angiogenesis assays',
      'Comparative peptide-stability research',
      'Reference standard for HPLC method development',
    ],
    included: [
      'Pre-filled research pen · 40mg total (4 × 10mg)',
      'Batch-specific Janoshik Certificate of Analysis',
      'Material Safety Data Sheet (MSDS)',
      'Reconstitution & storage guidelines',
      'Research information sheet',
    ],
    coa: {
      image: '/images/certificates/alluvi-bpc-tb500-coa.png',
      sampleImages: [
        '/images/certificates/alluvi-bpc-tb500-sample-1.jpg',
        '/images/certificates/alluvi-bpc-tb500-sample-2.jpg',
      ],
      batch: 'BP1701FSR',
      taskId: '163218',
      purity: 'ID & amount verified',
      testDate: '14 May 2026',
      verifyUrl: 'https://verify.janoshik.com/tests/163218-ALLUVI_BPC157_TB500_40MG_KIT_EAI125ZEF8TB',
      fillVolume: '2.4 mL',
      compound: 'BPC-157 + TB-500',
      sequence: 'C62H98N16O22 · C212H350N56O78S',
      concentrationLabel: '7.33 mg/mL · 6.53 mg/mL',
      totalContent: '4 × 10 mg blend',
    },
  },
  {
    id: 'retatrutide-20',
    slug: 'retatrutide-20mg',
    name: 'Retatrutide 20mg',
    tagline: 'Metabolic · Glucose · Energy',
    category: 'Triple Agonist',
    desc: 'A triple-agonist research peptide studied for its effects on metabolic regulation and body composition outcomes.',
    longDesc:
      'A 20mg Retatrutide formulation supplied in a pre-filled research device, provided exclusively for controlled laboratory R&D applications. Delivered in sealed format to support compound stability analysis, formulation studies, and delivery mechanism evaluation.',
    price: 100,
    currency: 'USD',
    accent: '#7A8F87',
    tint: '#EAF0EC',
    image: '/images/products/retatrutide-20-front.jpg',
    gallery: [
      '/images/products/retatrutide-20-front.jpg',
      '/images/products/retatrutide-20-open.jpg',
      '/images/products/retatrutide-20-pen.jpg',
      '/images/products/retatrutide-20-uv.jpg',
    ],
    stat: '99.3% HPLC purity',
    specs: [
      { k: 'Purity', v: '99.27%+ HPLC verified' },
      { k: 'Testing', v: 'Janoshik independent COA' },
      { k: 'Format', v: 'Pre-filled research pen · 4 × 5mg' },
      { k: 'Storage', v: '2–8°C · Do not freeze' },
      { k: 'Shelf life', v: '24–36 months sealed' },
    ],
    mechanism:
      'Retatrutide activates GIP, GLP-1 and glucagon receptors simultaneously — a triple-agonist profile investigated for its downstream effects on insulin sensitivity, satiety signalling and lipolysis. The 20mg configuration is well-suited to comparative dose-response research.',
    benefits: [
      'Multi-pathway metabolic modelling',
      'Insulin & glucose response research',
      'Appetite-signalling pathway studies',
      'Lipolysis and energy-expenditure assays',
      'Comparative receptor-affinity investigations',
      'Body-composition outcome modelling',
    ],
    applications: [
      'Dose-response comparative studies',
      'Receptor-signalling investigations',
      'Pharmacokinetic profiling',
      'Formulation and delivery-mechanism evaluation',
    ],
    included: [
      'Pre-filled research pen · 20mg total (4 × 5mg)',
      'Batch-specific Janoshik Certificate of Analysis',
      'Material Safety Data Sheet (MSDS)',
      'Reconstitution & storage guidelines',
      'Research information sheet',
    ],
    coa: {
      image: '/images/certificates/alluvi-retatrutide-20mg-coa.png',
      sampleImages: [
        '/images/certificates/alluvi-retatrutide-20mg-sample-1.jpg',
        '/images/certificates/alluvi-retatrutide-20mg-sample-2.jpg',
      ],
      batch: 'AR1721TRT',
      taskId: '163215',
      purity: '99.216%',
      testDate: '14 May 2026',
      verifyUrl: 'https://verify.janoshik.com/tests/163215-ALLUVI_RETATRUTIDE_20MG_KIT_GBHEFN58JXXZ',
      fillVolume: '2.4 mL',
      compound: 'Retatrutide',
      sequence: 'C221H343N53O68',
      concentrationLabel: '9.57 mg/mL',
      totalContent: '22.96 mg',
    },
  },
  {
    id: 'retatrutide',
    slug: 'retatrutide-40mg',
    name: 'Retatrutide 40mg',
    tagline: 'Metabolic · Glucose · Energy',
    category: 'Triple Agonist',
    desc: 'A triple-agonist research peptide studied for its effects on metabolic regulation and body composition outcomes.',
    longDesc:
      'Retatrutide 40mg pre-filled into an Alluvi research pen (4 × 10mg doses). A triple receptor agonist targeting GLP-1, GIP and glucagon pathways — the same molecule that produced an average 22.5% weight reduction in published Phase 2 clinical data. Independently Janoshik-verified across a 56-day stability window for metabolic-pathway R&D.',
    price: 180,
    currency: 'USD',
    accent: '#6B7F78',
    tint: '#E7EDE9',
    image: '/images/products/retatrutide-front.webp',
    gallery: [
      '/images/products/retatrutide-front.webp',
      '/images/products/retatrutide-open.webp',
      '/images/products/retatrutide-pen.webp',
      '/images/products/retatrutide-uv.webp',
    ],
    stat: '99.4% HPLC purity',
    specs: [
      { k: 'Purity', v: '99.38%+ HPLC verified' },
      { k: 'Testing', v: 'Janoshik 56-day stability' },
      { k: 'Format', v: 'Pre-filled research pen · 4 × 10mg' },
      { k: 'Storage', v: '2–8°C · Do not freeze' },
      { k: 'Shelf life', v: '24–36 months sealed' },
    ],
    mechanism:
      'Retatrutide is the first triple hormone receptor agonist to activate GIP, GLP-1 and glucagon pathways in a single molecule. This multi-pathway approach is investigated for enhanced glycaemic control, satiety induction, thermogenesis and hepatic lipid metabolism relative to single- or dual-agonist references.',
    benefits: [
      'Triple-agonist metabolic modelling',
      'Body-composition outcome research (per Phase 2 references)',
      'Glucose regulation & insulin sensitivity assays',
      'Appetite and satiety pathway studies',
      'Hepatic lipid metabolism investigations',
      'Thermogenesis and energy-expenditure modelling',
    ],
    applications: [
      'Comparative triple- vs. dual-agonist studies',
      '56-day stability window evaluation',
      'Receptor-binding affinity investigations',
      'Pre-clinical pharmacokinetic profiling',
    ],
    included: [
      'Pre-filled research pen · 40mg total (4 × 10mg)',
      'Batch-specific Janoshik Certificate of Analysis',
      'Material Safety Data Sheet (MSDS)',
      'Reconstitution & storage guidelines',
      'Research information sheet',
    ],
    coa: {
      image: '/images/certificates/alluvi-retatrutide-40mg-coa.png',
      sampleImages: [
        '/images/certificates/alluvi-retatrutide-40mg-sample-1.jpg',
        '/images/certificates/alluvi-retatrutide-40mg-sample-2.jpg',
      ],
      batch: 'AR1739JAT',
      taskId: '163216',
      purity: '99.269%',
      testDate: '14 May 2026',
      verifyUrl: 'https://verify.janoshik.com/tests/163216-ALLUVI_RETATRUTIDE_40MG_KIT_TU3SQLQB9ZDQ',
      fillVolume: '2.4 mL',
      compound: 'Retatrutide',
      sequence: 'C221H343N53O68',
      concentrationLabel: '18.22 mg/mL',
      totalContent: '43.72 mg verified',
    },
  },
  {
    id: 'tirzepatide',
    slug: 'tirzepatide-40mg',
    name: 'Tirzepatide 40mg',
    tagline: 'GLP-1 · GIP · Glucose',
    category: 'GLP-1 / GIP',
    desc: 'A dual GIP/GLP-1 receptor agonist studied for glucose response and appetite regulation in research settings.',
    longDesc:
      'Tirzepatide 40mg (4 × 10mg doses) pre-filled into an Alluvi research pen. A dual receptor agonist of GLP-1 (glucagon-like peptide-1) and GIP (glucose-dependent insulinotropic polypeptide) — studied in metabolic pharmacology models for insulin sensitivity, satiety and glucose homeostasis. Approximately 22% weight-reduction outcomes are reported in the published clinical literature this compound derives from.',
    price: 100,
    currency: 'USD',
    accent: '#7E8FA6',
    tint: '#E6EAF0',
    image: '/images/products/tirzepatide-front.webp',
    gallery: [
      '/images/products/tirzepatide-front.webp',
      '/images/products/tirzepatide-open.webp',
      '/images/products/tirzepatide-pen.webp',
      '/images/products/tirzepatide-uv.webp',
    ],
    stat: '99.1% HPLC purity',
    specs: [
      { k: 'Purity', v: '99.15%+ HPLC verified' },
      { k: 'Testing', v: 'Janoshik independent COA' },
      { k: 'Format', v: 'Pre-filled research pen · 4 × 10mg' },
      { k: 'Storage', v: '2–8°C · Do not freeze' },
      { k: 'Shelf life', v: '24–36 months sealed' },
    ],
    mechanism:
      'Tirzepatide simultaneously engages GLP-1 and GIP receptors, producing complementary incretin effects. Its dual action is investigated for enhanced insulinotropic response, delayed gastric emptying and central appetite modulation — a reference profile widely used in endocrine and metabolic disease pharmacology models.',
    benefits: [
      'Dual-incretin pathway modelling',
      'Metabolic disease pharmacology research',
      'Obesity mechanism investigations',
      'Type 2 diabetes therapeutic modelling',
      'Endocrine-system regulation studies',
      'Gastric-emptying and satiety assays',
    ],
    applications: [
      'In-vitro and in-vivo pre-clinical investigations',
      'GLP-1 vs. dual-agonist comparative studies',
      'Formulation and reconstitution research',
      'Reference standard for method development',
    ],
    included: [
      'Pre-filled research pen · 40mg total (4 × 10mg)',
      'Batch-specific Janoshik Certificate of Analysis',
      'Material Safety Data Sheet (MSDS)',
      'Reconstitution & storage guidelines',
      'Research information sheet',
    ],
    coa: {
      image: '/images/certificates/alluvi-tirzepatide-40mg-coa.png',
      sampleImages: [
        '/images/certificates/alluvi-tirzepatide-40mg-sample-1.jpg',
        '/images/certificates/alluvi-tirzepatide-40mg-sample-2.jpg',
        '/images/certificates/alluvi-tirzepatide-40mg-sample-3.jpg',
      ],
      batch: 'TR786PAOS',
      taskId: '147174',
      purity: '99.858%',
      testDate: '20 Apr 2026',
      verifyUrl: 'https://verify.janoshik.com/tests/147174-ALLUVI_TIRZEPATIDE_40MG_KIT_T5MBWRAYD4HN',
      fillVolume: '2.4 mL',
      compound: 'Tirzepatide',
      sequence: 'C225H348N48O68',
      concentrationLabel: '13.35 mg/mL',
      totalContent: '32.04 mg verified',
    },
  },
  {
    id: 'glow',
    slug: 'glow-70mg',
    name: 'Glow 70mg (GHK-Cu)',
    tagline: 'Skin · Radiance · Repair',
    category: 'Copper Peptide',
    desc: 'A copper-peptide studied in dermal research for collagen support, skin elasticity and visible radiance.',
    longDesc:
      'Glow 70mg GHK-Cu pre-filled into an Alluvi research pen. GHK-Cu (glycyl-L-histidyl-L-lysine copper) is a naturally-occurring tripeptide-copper complex found in human plasma, saliva and urine — declining significantly with age. This research formulation supports dermal-research evaluation of collagen synthesis, skin-barrier and repair pathways.',
    price: 100,
    currency: 'USD',
    accent: '#B9A37E',
    tint: '#F3EEE2',
    image: '/images/products/glow-front.webp',
    gallery: [
      '/images/products/glow-front.webp',
      '/images/products/glow-open.webp',
      '/images/products/glow-pen.webp',
      '/images/products/glow-uv.webp',
    ],
    stat: '99.5% HPLC purity',
    specs: [
      { k: 'Purity', v: '99.52%+ HPLC verified' },
      { k: 'Testing', v: 'Janoshik independent COA' },
      { k: 'Format', v: 'Pre-filled research pen · 70mg' },
      { k: 'Storage', v: '2–8°C · Do not freeze' },
      { k: 'Shelf life', v: '24–36 months sealed' },
    ],
    mechanism:
      'GHK-Cu upregulates growth factors and modulates inflammatory response — investigated in skin-research models for its ability to encourage collagen and elastin synthesis, reduce oxidative damage and support tissue remodelling. The copper chelation is central to its biological activity profile.',
    benefits: [
      'Collagen synthesis stimulation research',
      'Elastin production pathway studies',
      'Wound-healing acceleration assays',
      'Cellular-level skin regeneration modelling',
      'Antioxidant activity investigations',
      'Hair follicle stimulation studies',
    ],
    applications: [
      'Dermal-repair research models',
      'Oxidative-damage reduction assays',
      'Comparative cosmetic-peptide studies',
      'Skin-barrier and follicle research protocols',
    ],
    included: [
      'Pre-filled research pen · 70mg GHK-Cu',
      'Batch-specific Janoshik Certificate of Analysis',
      'Material Safety Data Sheet (MSDS)',
      'Reconstitution & storage guidelines',
      'Research information sheet',
    ],
    coa: {
      image: '/images/certificates/alluvi-glow-70mg-coa.png',
      sampleImages: [
        '/images/certificates/alluvi-glow-70mg-sample-1.jpg',
        '/images/certificates/alluvi-glow-70mg-sample-2.jpg',
      ],
      batch: 'GL0621XSA',
      taskId: '163217',
      purity: 'ID & amount verified',
      testDate: '14 May 2026',
      verifyUrl: 'https://verify.janoshik.com/tests/163217-ALLUVI_GLOW_70MG_KIT_DCL3AJSE4JQP',
      fillVolume: '2.4 mL',
      compound: 'GHK-Cu · BPC-157 · TB-500 (KLOW blend)',
      sequence: 'C14H24CuN6O4 · C62H98N16O22 · C212H350N56O78S',
      concentrationLabel: '7.59 · 2.39 · 1.99 mg/mL',
      totalContent: '4 × 10 mg blend',
    },
  },
  {
    id: 'nad-plus',
    slug: 'nad-plus-1000mg',
    name: 'NAD+ 1,000mg',
    tagline: 'Cellular · Longevity · Energy',
    category: 'Coenzyme',
    desc: 'A Nicotinamide Adenine Dinucleotide research formulation studied for cellular energetics, redox balance and longevity pathways.',
    longDesc:
      'NAD+ (Nicotinamide Adenine Dinucleotide) supplied as two pre-filled 500mg pens (1,000mg total) for laboratory analysis and in-vitro study. NAD+ is the primary coenzyme powering hundreds of cellular metabolic processes — including mitochondrial energy production, DNA repair signalling (PARP, sirtuins) and redox balance. Levels decline significantly with age, making this a central molecule in longevity-pathway research.',
    price: 140,
    currency: 'USD',
    accent: '#7A6FA8',
    tint: '#ECE9F3',
    image: '/images/products/nad-front.jpg',
    gallery: [
      '/images/products/nad-front.jpg',
      '/images/products/nad-open.jpg',
      '/images/products/nad-pen.jpg',
      '/images/products/nad-uv.jpg',
    ],
    stat: '99.0% HPLC purity',
    specs: [
      { k: 'Purity', v: '99.06%+ HPLC verified' },
      { k: 'Testing', v: 'Janoshik independent COA' },
      { k: 'Format', v: '2 × pre-filled 500mg pens' },
      { k: 'Storage', v: '2–8°C · Do not freeze' },
      { k: 'Shelf life', v: '24–36 months sealed' },
    ],
    mechanism:
      'NAD+ acts as a hydride carrier and substrate for sirtuins and PARP enzymes — driving mitochondrial oxidative phosphorylation, DNA-repair signalling and cellular redox balance. Restoring intracellular NAD+ pools is a central hypothesis in longevity and mitochondrial-health research.',
    benefits: [
      'Cellular energy restoration research',
      'Mitochondrial-function modelling',
      'DNA-repair pathway (PARP/sirtuin) studies',
      'Longevity and biological-ageing marker research',
      'Cognitive performance and mental-clarity assays',
      'Muscle recovery and endurance investigations',
    ],
    applications: [
      'In-vitro mitochondrial energetics studies',
      'Sirtuin activity assays',
      'Comparative redox-balance research',
      'Longevity protocol reference standard',
    ],
    included: [
      '2 × pre-filled research pens · 500mg each',
      'Batch-specific Janoshik Certificate of Analysis',
      'Material Safety Data Sheet (MSDS)',
      'Reconstitution & storage guidelines',
      'Research information sheet',
    ],
    coa: {
      image: '',
      batch: 'Batch-specific COA on request',
      taskId: '—',
      purity: 'Manufacturer verified',
      testDate: 'See dispatched batch',
      verifyUrl: 'https://verify.janoshik.com/',
      fillVolume: '2.4 mL',
      compound: 'NAD+',
      sequence: 'C21H27N7O14P2',
      concentrationLabel: '208.33 mg/mL',
      totalContent: '1,000 mg',
    },
  },
] as const

export const INGREDIENTS = [
  {
    name: 'Marine Collagen',
    latin: 'Hydrolyzed Type I',
    note: 'Peptide-perfect for elasticity, bounce and visible glow.',
    image: IMG.ingredientCollagen,
  },
  {
    name: 'Ashwagandha',
    latin: 'KSM-66®',
    note: 'A clinically-studied adaptogen that calms cortisol and steadies energy.',
    image: IMG.ingredientAdaptogen,
  },
  {
    name: 'Omega-3 DHA',
    latin: 'Algae-derived',
    note: 'Plant-sourced essential fats for brain, heart and cellular health.',
    image: IMG.ingredientOmega,
  },
  {
    name: 'Organic Greens',
    latin: 'Spirulina · Chlorella',
    note: 'Cold-processed phytonutrients delivering whole-food micronutrition.',
    image: IMG.ingredientGreens,
  },
] as const

export const STATS = [
  { value: 47, suffix: '+', label: 'Peer-reviewed studies referenced' },
  { value: 100, suffix: '%', label: 'Traceable, third-party tested actives' },
  { value: 92, suffix: '%', label: 'Reported better energy in 8 weeks' },
  { value: 0, prefix: '', suffix: '', label: 'Fillers, dyes & synthetic additives', display: 'Zero' },
] as const

export const BENEFITS = [
  { k: '01', t: 'Visible Radiance', d: 'Skin that looks lit from within — elasticity, hydration and even tone.', image: '/images/jupyter-labs/visible-radiance-benefit.webp' },
  { k: '02', t: 'Sustained Energy', d: 'Clean vitality without the spike-and-crash of stimulants.', image: '/images/jupyter-labs/sustained-energy-benefit.webp' },
  { k: '03', t: 'Deep Recovery', d: 'Calmer nights and sharper mornings through restorative sleep.', image: '/images/jupyter-labs/deep-recovery-benefit.webp' },
  { k: '04', t: 'Resilient Immunity', d: 'A fortified daily baseline so you stay your strongest self.', image: '/images/jupyter-labs/resilient-immunity-benefit.webp' },
] as const

export const TESTIMONIALS = [
  {
    name: 'Amara N.',
    role: 'Creative Director',
    quote: 'Jupyter Labs replaced a shelf of supplements with two elegant rituals. My skin and focus have never been better.',
    image: '/images/jupyter-labs/customer-stories/customer-testimonial-amara-creative-director.webp',
  },
  {
    name: 'Julien M.',
    role: 'Endurance Athlete',
    quote: 'The transparency is unreal — every active is dosed to the studies. I feel the difference by week three.',
    image: '/images/jupyter-labs/customer-stories/customer-testimonial-julien-endurance-athlete.webp',
  },
  {
    name: 'Sofia R.',
    role: 'Founder',
    quote: 'It feels less like taking vitamins and more like a daily moment of luxury. Obsessed.',
    image: '/images/jupyter-labs/customer-stories/customer-testimonial-sofia-founder.webp',
  },
  {
    name: 'Daniel K.',
    role: 'Physician',
    quote: 'Finally a brand I can recommend. Clinically-relevant doses, clean sourcing, zero marketing fluff.',
    image: '/images/jupyter-labs/customer-stories/customer-testimonial-daniel-physician.webp',
  },
  {
    name: 'Lina P.',
    role: 'Yoga Teacher',
    quote: 'Calm changed my sleep within a week. I wake up genuinely rested for the first time in years.',
    image: '/images/jupyter-labs/customer-stories/customer-testimonial-lina-yoga-teacher.webp',
  },
  {
    name: 'Marcus T.',
    role: 'Investor',
    quote: 'Performance you can feel and chemistry you can verify. Jupyter Labs is the new standard.',
    image: '/images/jupyter-labs/customer-stories/customer-testimonial-marcus-investor.webp',
  },
] as const

export const TRUST = [
  'Third-Party Tested',
  'cGMP Certified',
  'Vegan & Non-GMO',
  'Climate Neutral',
  'No Fillers',
  'Clinically Dosed',
] as const

export const TIMELINE = [
  { year: '2019', t: 'The Question', d: 'Two scientists ask why wellness has to choose between efficacy and elegance.' },
  { year: '2021', t: 'The Formulas', d: 'Three years of research distilled into clinically-dosed, traceable rituals.' },
  { year: '2023', t: 'The Launch', d: 'Jupyter Labs debuts to a waitlist of 40,000 — sold out in nineteen hours.' },
  { year: 'Today', t: 'The Standard', d: 'A new benchmark for what science-backed luxury wellness can be.' },
] as const

export const NAV = [
  { label: 'Home', href: '#top' },
  { label: 'About', href: '#about' },
  { label: 'Products', href: '#products' },
  { label: 'Why Us', href: '#why' },
  { label: 'Testimonials', href: '#testimonials' },
  { label: 'Contact', href: '#contact' },
] as const
